// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWTLPE-xhOR4TAo6JQE68HhY107BLEtss',
    appId: '1:1022372894594:web:41959b500dbe12831e619b',
    messagingSenderId: '1022372894594',
    projectId: 'poojajadhav-afcac',
    authDomain: 'poojajadhav-afcac.firebaseapp.com',
    databaseURL: 'https://poojajadhav-afcac-default-rtdb.firebaseio.com',
    storageBucket: 'poojajadhav-afcac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO2ahp1O16uuySgq6I0X6M8mKDhESqDDY',
    appId: '1:1022372894594:android:ef6bb3ae1c7594ed1e619b',
    messagingSenderId: '1022372894594',
    projectId: 'poojajadhav-afcac',
    databaseURL: 'https://poojajadhav-afcac-default-rtdb.firebaseio.com',
    storageBucket: 'poojajadhav-afcac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA2L8hP1OqkzKmG82nsmUtORXpuhynxcU',
    appId: '1:1022372894594:ios:347854c1d6aef4dc1e619b',
    messagingSenderId: '1022372894594',
    projectId: 'poojajadhav-afcac',
    databaseURL: 'https://poojajadhav-afcac-default-rtdb.firebaseio.com',
    storageBucket: 'poojajadhav-afcac.firebasestorage.app',
    iosBundleId: 'com.example.cleanMvvmPattern',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA2L8hP1OqkzKmG82nsmUtORXpuhynxcU',
    appId: '1:1022372894594:ios:347854c1d6aef4dc1e619b',
    messagingSenderId: '1022372894594',
    projectId: 'poojajadhav-afcac',
    databaseURL: 'https://poojajadhav-afcac-default-rtdb.firebaseio.com',
    storageBucket: 'poojajadhav-afcac.firebasestorage.app',
    iosBundleId: 'com.example.cleanMvvmPattern',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWTLPE-xhOR4TAo6JQE68HhY107BLEtss',
    appId: '1:1022372894594:web:7039c439881cafc31e619b',
    messagingSenderId: '1022372894594',
    projectId: 'poojajadhav-afcac',
    authDomain: 'poojajadhav-afcac.firebaseapp.com',
    databaseURL: 'https://poojajadhav-afcac-default-rtdb.firebaseio.com',
    storageBucket: 'poojajadhav-afcac.firebasestorage.app',
  );
}
